### ISSUE TITLE
Project Guidelines

### ISSUE THREAD

**Issue by ugnelis** [ms-iot/winml_tracker#6]
Good Day,

Good you tell me what kind of guidelines are you following in this ROS package? Because I've noticed that there are different naming styles, usage of namespace and etc.

Best Regards,
Ugnius Malukas

**Comment by ooeygui** [comment]
Hi @ugnelis,
This package used internal guidelines on naming styles and namespaces. It references the WinRT APIs to reference WinML, and OpenCV, both of which have their own conventions. We're working on refactoring this to support ROS1 and ROS2, so some of that will also enter the codebase.
